version: '3.5'

services:
  database:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=locacar"
    volumes:
      - data:/var/lib/postgres/data/pgdata
      - pg-config:/etc/postgresql
    # entrypoint: docker-entrypoint.sh -c 'config_file=/mnt/d/docker/postgres_custom/postgresql.config'
volumes:
  data:
  pg-config:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "$PWD/postegres_custom"